<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Probook15-650Series" failures="3" tests="6" name="Test" time="38.61" errors="0" timestamp="2023-04-15T11:20:53 GST">
  <testcase classname="com.obsqura.testScripts.LoginTest" name="verify_login_with_Credentials" time="1.399"/>
  <testcase classname="com.obsqura.testScripts.LoginTest" name="verify_login_with_Credentials" time="0.661">
    <failure type="java.lang.AssertionError" message="Login failed expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]">
      <![CDATA[java.lang.AssertionError: Login failed expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]
at com.obsqura.testScripts.LoginTest.verify_login_with_Credentials(LoginTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- verify_login_with_Credentials -->
  <testcase classname="com.obsqura.testScripts.LoginTest" name="verify_login_with_Credentials" time="0.616">
    <failure type="java.lang.AssertionError" message="Login failed expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]">
      <![CDATA[java.lang.AssertionError: Login failed expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]
at com.obsqura.testScripts.LoginTest.verify_login_with_Credentials(LoginTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- verify_login_with_Credentials -->
  <testcase classname="com.obsqura.testScripts.LoginTest" name="verify_login_with_Credentials" time="0.584">
    <failure type="java.lang.AssertionError" message="Login failed expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]">
      <![CDATA[java.lang.AssertionError: Login failed expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]
at com.obsqura.testScripts.LoginTest.verify_login_with_Credentials(LoginTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- verify_login_with_Credentials -->
  <testcase classname="com.obsqura.testScripts.ManagepageTest" name="verify_newButton" time="3.79"/>
  <testcase classname="com.obsqura.testScripts.ManagepageTest" name="verify_searchButton" time="1.697"/>
</testsuite> <!-- Test -->
